server:
  port: 10010

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service  # 路由id，没有固定规则但要求唯一，建议配合服务名使用
          uri: lb://user-service # 匹配后提供服务的路由地址
          predicates:
            - Path=/user-service/** # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1  #截取访问过来的url Path配置的路径user-service以后的路径进行使用
        - id: consumer  # 路由id，没有固定规则但要求唯一，建议配合服务名使用
          uri: lb://consumer # 匹配后提供服务的路由地址
          predicates:
            - Path=/consumer/** # 断言，路径相匹配的进行路由
          filters:
            - StripPrefix=1 #截取访问过来的url Path配置的路径consumer以后的路径进行使用

eureka:
  instance:
    hostname: cloud-gateway-service
  client:    #  服务提供者provider注册金eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:10086/eureka/
