server:
  port: 8081
spring:
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ribbon:
  ConnectTimeout: 250
  ReadTimeout: 1000


user-service:
  ribbon:
    ConnectTimeout: 250
    ReadTimeout: 1000
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 1000
        read-timeout: 1000
